UsingViewComponents/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public class City
    {
        public string Name { get; set; }
        public string Country { get; set; }
        public int Population { get; set; }
    }
}

UsingViewComponents/Models/CityRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public interface ICityRepository
    {
         IEnumerable<City> Cities { get; }
        void AddCity(City newCity);
    }
    public class MemoryCityRepository:ICityRepository
    {
        private List<City> cities = new List<City>
        {
            new City {Name = "London", Country = "UK", Population = 8539000},
            new City {Name = "New York", Country = "USA", Population = 8406000},
            new City {Name = "San Jose", Country = "USA", Population = 998537},
            new City {Name = "Paris", Country = "France", Population = 2244000},
        };

        public IEnumerable<City> Cities => cities;
        public void AddCity(City newCity)
        {
            cities.Add(newCity);
        }
    }
}

UsingViewComponents/Models/CityViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public class CityViewModel
    {
        public int Cities { get; set; }
        public int Population { get; set; }
    }
}

UsingViewComponents/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public class Product
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}

UsingViewComponents/Models/ProductRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UsingViewComponents.Models
{
    public interface IProductRepository
    {
         IEnumerable<Product> Products { get;  }
        void AddProduct(Product newProduct);
    }

    public class MemoryProductRepository : IProductRepository
    {
        private List<Product> products = new List<Product>
        {
            new Product {Name = "Kayak", Price = 275M},
            new Product {Name = "Lifejacket", Price = 48.95M},
            new Product {Name = "Soccer ball", Price = 19.50M},
            new Product {Name = "Corner flag", Price = 34.95M},
        };

        public IEnumerable<Product> Products => products;
        public void AddProduct(Product newProduct)
        {
            products.Add(newProduct);
        }
    }
}

UsingViewComponents/Components/PocoViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UsingViewComponents.Models;

namespace UsingViewComponents.Components
{   //Plain out c# object; a component built without using the ViewComponent base class(MVC api)
    public class PocoViewComponent
    {   
//    creates a dependency on ICityRepository interface -- anyone of the repos implementing this interface can be used, and it designated in the setup file
        //dependency injection provides the class with the services it requires
        private ICityRepository _repository;

        public PocoViewComponent(ICityRepository repo)
        {
            _repository = repo;
        }
        //Invoke method describes the component that will be inserted into the parent view(in this case,_Layout) using @await Component.InvokeAsync("Poco")
        public string Invoke()
        {
            return $"{_repository.Cities.Count()} cities, "
                   + $"{_repository.Cities.Sum(c => c.Population)} people";
        }

    }
}

UsingViewComponents/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using UsingViewComponents.Models;


namespace UsingViewComponents.Controllers
{
    [ViewComponent(Name = "ComboComponent")]
    public class CityController : Controller
    {
        private ICityRepository _repository;

        public CityController(ICityRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(City newCity)
        {
            _repository.AddCity(newCity);
            return RedirectToAction("Index", "Home");
        }

        public IViewComponentResult Invoke()
        {
            return new ViewViewComponentResult() {
                ViewData = new ViewDataDictionary<IEnumerable<City>>(ViewData, _repository.Cities)
                
                };
        }
        }
    }

UsingViewComponents/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UsingViewComponents.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace UsingViewComponents.Controllers
{


    public class HomeController : Controller
    {

        private IProductRepository _repository;

        //ctor with dependency on IProductRepository. When Mvc inits controller, it will consult service provider in setup, which will pass in the IPR object.
        public HomeController(IProductRepository repo)
        {
            _repository = repo;
        }


        public IActionResult Index()
        {
            return View(_repository.Products);
        }


        //following 2 methods use the Post/redirect/Get pattern for handling form data
        public ViewResult Create() => View();

        [HttpPost]
        public IActionResult Create(Product newProduct)
        {
            _repository.AddProduct(newProduct);
            return RedirectToAction("Index");
        }
        
    }
    
}

UsingViewComponents/Views/City/Create.cshtml
@model City
@{
    ViewData["Title"] = "Create City";
    Layout = "_Layout";
}

<form asp-action="Create" method="post">
    <div>
        <label asp-for="Name">Name:</label>
        <input class="form-control" asp-for="Name"/>
    </div>
    <div>
        <label asp-for="Country">Country:</label>
        <input class="form-control" asp-for="Country"/>
    </div>    <div>
        <label asp-for="Population">Population:</label>
        <input class="form-control" asp-for="Population"/>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    <a class="btn btn-secondary" asp-controller="Home"asp-action="Index">Cancel</a>
</form>

UsingViewComponents/Views/Home/Components/PageSize/Default.cshtml
@model long

@Model (from the Pagesize class/default view)

UsingViewComponents/Views/Home/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Create Product";
    Layout = "_Layout";
}

<form asp-action="Create" method="post">
    <div>
        <label asp-for="Name">Name:</label>
        <input class="form-control" asp-for="Name"/>
        </div>
    <div>
        <label asp-for="Price">Price:</label>
        <input class="form-control" asp-for="Price"/>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    <a class="btn btn-secondary" asp-action="Index">Cancel</a>
</form>

UsingViewComponents/Views/Home/Index.cshtml
@*//View that displays the products and included button targeting Create action to render form to create a product*@

@model IEnumerable<Product>

@{
    ViewData["Title"] = "Products";
    Layout = "_Layout";
}
<table class="table table-sm table-striped table-bordered">
    <thead>
    <tr><th>Name</th><th>Price</th></tr>
    </thead>
    <tbody>
    @foreach (var product in Model)
    {
        <tr><td>@product.Name</td>
            <td>@product.Price</td></tr>
    }
    </tbody>
</table>
<a asp-action="Create" class="btn btn-primary">Create</a>

UsingViewComponents/Views/Shared/Components/CitySummary/CityList.cshtml
@model IEnumerable<City>

<table class="table table-sm table-bordered">
    @foreach(var city in Model){<tr>
        <td>@city.Name</td>
        <td class="text-right">@city.Population.ToString("##,###")</td>
    </tr>}
    <tr>
        <td>Total: </td>
        <td class="text-right">@Model.Sum(p => p.Population).ToString("##,###")</td>
    </tr>
</table>

UsingViewComponents/Views/Shared/Components/CitySummary/Default.cshtml
@model CityViewModel

<table class="table table-sm table-bordered">
    <tr>
        <td>Cities:</td>
        <td class="text-right">@Model.Cities</td>
    </tr>    <tr>
        <td>Population:</td>
        <td class="text-right">@Model.Population.ToString("##,###")</td>
    </tr>
</table>

UsingViewComponents/Views/Shared/Components/ComboComponent/Default.cshtml
@model IEnumerable<City>

<table>
    <tr>
        <td>Biggest City: </td>
        <td>@Model.OrderByDescending(c=>c.Population).First().Name</td>
        
    </tr>
</table>
<a class="btn btn-sm btn-info" asp-controller="City" asp-action="Create">Create</a>

UsingViewComponents/Views/Shared/_Layout.cshtml
@using System.ComponentModel
@using UsingViewComponents.Components
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link asp-href-include="/lib/bootstrap/dist/css/*.min.css" rel="stylesheet" />
</head>
<body class="m-1 p-1">
<div class="m-1 p-1 bg-primary">
    <div class="row text-white">
        <div class="col-7">
            <h1>Products</h1>
            
        </div>
        <div class="col-5">
            3 invoke statements that display 3 differenct components from within the layout
            @*            simple invoke method that produces component in layout where showlist== false by defaut *@
            <div class="">@await Component.InvokeAsync(nameof(CitySummary)) </div>

            @*            invoke statement that passes in additional information to choose which component to render in layout*@

            <div>@await Component.InvokeAsync("CitySummary", new {showlist = true})</div>

@*            invoke statement that delivers content from 3rd party in the*@
@*            <div>@await Component.InvokeAsync("PageSize")</div>*@
            
            <div>@await Component.InvokeAsync("ComboComponent")</div>


        </div>
    </div>
</div>
<div class="m-1 p-1">
    @RenderBody()
</div>
</body>
</html>